services:
  - type: web
    name: freelanceos-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: DATABASE_URL
        value: postgresql://postgres:Anshul-777%40@db.zxsloquwsmicadpanclo.supabase.co:5432/postgres?sslmode=require
      - key: FRONTEND_URL
        value: https://freelance-os-system-w8mv.vercel.app
      - key: BACKEND_URL
        value: https://freelance-os-system.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: RESEND_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
