import csv
import io
from typing import List, Dict, Any, Optional
from decimal import Decimal
from datetime import date
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph,
    Spacer, HRFlowable
)
from reportlab.lib.enums import TA_LEFT, TA_RIGHT, TA_CENTER

# Constants for branding
PRIMARY    = colors.HexColor("#1E293B")
ACCENT     = colors.HexColor("#4F46E5")
MUTED      = colors.HexColor("#64748B")
LIGHT_GRAY = colors.HexColor("#F1F5F9")
BORDER     = colors.HexColor("#E2E8F0")
WHITE      = colors.white

class ExportService:
    def generate_expense_csv(self, expenses: List[Any], workspace_name: str) -> str:
        """Generates a professional CSV string with branded headers and summary."""
        output = io.StringIO()
        writer = csv.writer(output)
        
        # Branded Header
        writer.writerow(["FREELANCE OS - EXPENSE REPORT"])
        writer.writerow([f"Workspace: {workspace_name}"])
        writer.writerow([f"Report Date: {date.today()}"])
        writer.writerow([f"Total Entries: {len(expenses)}"])
        writer.writerow([])
        
        # Column Headers
        writer.writerow([
            "ID", "Date", "Description", "Category", "Amount", 
            "Currency", "Tax Incl.", "Tax Amount", "Project", "Vendor", "Status"
        ])
        
        for e in expenses:
            status = "Billable" if e.is_billable else "Non-billable"
            if e.is_reimbursed:
                status += ", Reimbursed"
                
            project_name = e.project.name if e.project else "N/A"
            tax_incl = "Yes" if e.tax_included else "No"
            
            writer.writerow([
                e.id,
                e.date,
                e.description,
                e.category.value.replace("_", " ").title(),
                f"{e.amount:.2f}",
                e.currency,
                tax_incl,
                f"{e.tax_amount:.2f}" if e.tax_amount else "0.00",
                project_name,
                e.vendor or "—",
                status
            ])
            
        return output.getvalue()

    def generate_expense_pdf(self, expenses: List[Any], user: Any, workspace_name: str) -> bytes:
        """Generates a professional branded PDF report for expenses."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer, 
            pagesize=A4, 
            rightMargin=18*mm, 
            leftMargin=18*mm, 
            topMargin=15*mm, 
            bottomMargin=15*mm
        )
        styles = getSampleStyleSheet()
        
        # Custom Styles
        style_h1 = ParagraphStyle("H1", parent=styles["Normal"], fontSize=24, textColor=PRIMARY, fontName="Helvetica-Bold", leading=30)
        style_h3 = ParagraphStyle("H3", parent=styles["Normal"], fontSize=11, textColor=MUTED, fontName="Helvetica-Bold", leading=14)
        style_body = ParagraphStyle("Body", parent=styles["Normal"], fontSize=9, textColor=PRIMARY, leading=12)
        style_header = ParagraphStyle("Header", parent=styles["Normal"], fontSize=9, textColor=WHITE, fontName="Helvetica-Bold", alignment=TA_LEFT)
        style_footer = ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=MUTED, alignment=TA_CENTER)
        
        story = []
        
        # Header Section
        story.append(Paragraph("Expense Report", style_h1))
        story.append(Paragraph(workspace_name, style_h3))
        story.append(Spacer(1, 5*mm))
        story.append(HRFlowable(width="100%", thickness=1, color=BORDER, spaceAfter=8*mm))
        
        # Info Cells
        meta_data = [
            [Paragraph("GENERATED BY", style_header), Paragraph("REPORT DATE", style_header), Paragraph("ENTRIES", style_header)],
            [Paragraph(user.full_name, style_body), Paragraph(date.today().strftime("%B %d, %Y"), style_body), Paragraph(str(len(expenses)), style_body)]
        ]
        meta_table = Table(meta_data, colWidths=[60*mm, 60*mm, 54*mm])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), PRIMARY),
            ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
            ('PADDING', (0, 0), (-1, -1), 8),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 10*mm))
        
        # Table of Expenses
        item_header = [
            Paragraph("DATE", style_header),
            Paragraph("DESCRIPTION", style_header),
            Paragraph("CATEGORY", style_header),
            Paragraph("AMOUNT", style_header)
        ]
        
        table_data = [item_header]
        total_by_currency = {}
        
        for idx, e in enumerate(expenses):
            bg = LIGHT_GRAY if idx % 2 == 0 else WHITE
            table_data.append([
                Paragraph(str(e.date), style_body),
                Paragraph(e.description[:50], style_body),
                Paragraph(e.category.value.replace('_', ' ').title(), style_body),
                Paragraph(f"{e.amount:,.2f} {e.currency}", ParagraphStyle("Amt", parent=style_body, alignment=TA_RIGHT))
            ])
            total_by_currency[e.currency] = total_by_currency.get(e.currency, Decimal('0.00')) + Decimal(str(e.amount))
        
        col_widths = [30*mm, 80*mm, 34*mm, 30*mm]
        t = Table(table_data, colWidths=col_widths, repeatRows=1)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
            ('TEXTCOLOR', (0, 0), (-1, 0), WHITE),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('LINEBELOW', (0, 0), (-1, -2), 0.5, BORDER),
            ('BACKGROUND', (0, 1), (-1, -1), WHITE),
        ]))
        story.append(t)
        
        # Summary
        story.append(Spacer(1, 10*mm))
        if total_by_currency:
            story.append(Paragraph("SUMMARY BY CURRENCY", style_h3))
            for cur, amt in total_by_currency.items():
                story.append(Paragraph(f"• {cur}: {amt:,.2f}", style_body))
        
        # Footer
        story.append(Spacer(1, 20*mm))
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceAfter=2*mm))
        story.append(Paragraph(f"Generated by FreelanceOS — Your Business Operating System", style_footer))
        
        doc.build(story)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes

export_service = ExportService()
